# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: api-center-workshop
metadata:
    template: azd-init@1.11.0
services:
    flightsapi:
        project: src/api/flights
        host: containerapp
        language: js
        docker:
            remoteBuild: false
            path: Dockerfile
            registry: "docker.io"
            image: 'juliamuiruri4/contoso-air-flights'
    petsapi:
        project: src/api/petTravelCompanions
        host: function
        language: ts
    serviceapi:
        project: src/api/services
        host: appservice
        language: js
    website:
        project: ./src/client
        dist: ./
        host: staticwebapp
        language: js

hooks:
  postprovision: 
    windows:
      shell: pwsh
      run: |
        azd env get-values > src/api/services/.env
        azd env get-values > src/api/petTravelCompanions/.env
        azd env get-values > src/api/flights/.env
    posix:
      shell: sh
      run: |
        azd env get-values > src/api/services/.env
        azd env get-values > src/api/petTravelCompanions/.env
        azd env get-values > src/api/flights/.env
    interactive: true
    continueOnError: false
  prepackage:
    windows: 
      shell: pwsh
      run: |
        cd src/api/services && npm install && npm run
        cd ../../api/petTravelCompanions && npm install
        cd ../../api/flights && npm install
    posix: 
      shell: sh
      run: |
        cd src/api/services && npm install
        cd ../../api/petTravelCompanions && npm install
        cd ../../api/flights && npm install